# Generated by Django 2.2.7 on 2019-12-02 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_filljointable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
